# Generated by Django 5.0.7 on 2024-10-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_profile_national_code_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
