# Generated by Django 5.0.7 on 2024-09-02 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_category_alter_post_pub_date_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 11, 1, 31, 47139, tzinfo=datetime.timezone.utc)),
        ),
    ]
