# Generated by Django 5.0.7 on 2024-09-16 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_massage_alter_comment_parent_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 14, 47, 36, 739036, tzinfo=datetime.timezone.utc)),
        ),
    ]
