# Generated by Django 5.0.7 on 2024-09-20 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_rename_massage_message_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 11, 54, 7, 436802, tzinfo=datetime.timezone.utc)),
        ),
    ]
